name: mvvm_framework
description: "A Flutter package for implementing the MVVM architectural pattern with ease, built as an extension of Flutter Bloc."
version: 0.0.1
homepage: https://github.com/Draxent/mvvm_framework
repository: https://github.com/Draxent/mvvm_framework

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
